-- Migration: Add weekly schedule configuration to users table

-- Add JSONB column for weekly work schedule
ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS orari_settimanali JSONB DEFAULT NULL;

-- Add comment for documentation
COMMENT ON COLUMN public.users.orari_settimanali IS 'Configurazione orari settimanali con sessioni separate: { "lunedi": { "abilitato": true, "mattina_abilitata": true, "ingresso_mattina": "09:00", "uscita_mattina": "13:00", "pomeriggio_abilitato": true, "ingresso_pomeriggio": "15:00", "uscita_pomeriggio": "18:30" }, ... }';

-- Example structure (Full-time Lunedì-Venerdì):
-- {
--   "lunedi": {
--     "abilitato": true,
--     "mattina_abilitata": true,
--     "ingresso_mattina": "09:00",
--     "uscita_mattina": "13:00",
--     "pomeriggio_abilitato": true,
--     "ingresso_pomeriggio": "15:00",
--     "uscita_pomeriggio": "18:30"
--   },
--   "martedi": {
--     "abilitato": true,
--     "mattina_abilitata": true,
--     "ingresso_mattina": "09:00",
--     "uscita_mattina": "13:00",
--     "pomeriggio_abilitato": false,
--     "ingresso_pomeriggio": null,
--     "uscita_pomeriggio": null
--   },
--   "mercoledi": {
--     "abilitato": true,
--     "mattina_abilitata": true,
--     "ingresso_mattina": "09:00",
--     "uscita_mattina": "13:00",
--     "pomeriggio_abilitato": true,
--     "ingresso_pomeriggio": "15:00",
--     "uscita_pomeriggio": "18:30"
--   },
--   "giovedi": {
--     "abilitato": true,
--     "mattina_abilitata": true,
--     "ingresso_mattina": "09:00",
--     "uscita_mattina": "13:00",
--     "pomeriggio_abilitato": true,
--     "ingresso_pomeriggio": "15:00",
--     "uscita_pomeriggio": "18:30"
--   },
--   "venerdi": {
--     "abilitato": true,
--     "mattina_abilitata": true,
--     "ingresso_mattina": "09:00",
--     "uscita_mattina": "13:00",
--     "pomeriggio_abilitato": true,
--     "ingresso_pomeriggio": "15:00",
--     "uscita_pomeriggio": "18:30"
--   },
--   "sabato": {
--     "abilitato": false,
--     "mattina_abilitata": false,
--     "ingresso_mattina": null,
--     "uscita_mattina": null,
--     "pomeriggio_abilitato": false,
--     "ingresso_pomeriggio": null,
--     "uscita_pomeriggio": null
--   },
--   "domenica": {
--     "abilitato": false,
--     "mattina_abilitata": false,
--     "ingresso_mattina": null,
--     "uscita_mattina": null,
--     "pomeriggio_abilitato": false,
--     "ingresso_pomeriggio": null,
--     "uscita_pomeriggio": null
--   }
-- }
